config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  root to: 'pages#home'
  
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'angular-items', to: 'portfolios#angular'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  resources :portfolios, except:  [:show]
  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    enum status: {draft: 0, published: 1}
    extend FriendlyId
    friendly_id :title, use: :slugged

    validates :title, :body, presence: true, allow_blank: false

    belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
    extend ActiveSupport::Concern

    def self.image_generator(height:, width:)
        "https://place-hold.it/#{height}x#{width}"
    end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies, 
                                  reject_if: lambda { |attrs| attrs['name'].blank?}

    include Placeholder
    validates :title, :body, :main_image, :thumb_image, presence: true, allow_blank: false

    def self.angular
        where(subtitle: "Angular")
    end

    scope :ruby_on_rails_portfolio_items, -> {where(subtitle: "Ruby on Rails")}

    after_initialize :set_defaults

    def set_defaults
        self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
        self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
    end
end

app/models/skill.rb
class Skill < ApplicationRecord
    include Placeholder
    validates :title, :percent_utilized, presence: true, allow_blank: false

    after_initialize :set_defaults

    def set_defaults
        self.badge ||= Placeholder.image_generator(height: '250', width: '250')
    end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
    validates :title, presence: true, allow_blank: false

    has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, allow_blank: false

  def first_name
    self.name.split.first
  end
  
  def last_name
    self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include DeviseWhitelist
    include SetSource
    # include CurrentUserConcern
    include DefaultPageContent 
    
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy toggle_status ]
  layout "blog"

  def index
    @page_title = "My Portfolio Blog"
    @blogs = Blog.all
  end

  def show
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    else
      @blog.draft!
    end
    redirect_to blogs_url, notice: "Post status has been updated."
  end

  private
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
    extend ActiveSupport::Concern

    def current_user
        current_user || guest_user
    end

    def guest_user
        OpenStruct.new(name: "Guest User",
                        first_name: "Guest",
                        last_name: "User",
                        email: "guest@examplr.com")
    end
end

app/controllers/concerns/default_page_content.rb
module DefaultPageContent
    extend ActiveSupport::Concern

    included do
        before_action :set_page_defaults
    end

    def set_page_defaults
        @page_title = "Devcamp Portfolio | My Portfolio Website"
        @seo_keywords = "Devcamp portfolio"
    end

end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
    extend ActiveSupport::Concern

    included do
        before_action :configure_permitted_parameters, if: :devise_controller?
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/concerns/set_source.rb
module SetSource
    extend ActiveSupport::Concern
    
    included do
        before_action :set_source
    end
    
    def set_source
        session[:source] = params[:q] if params[:q]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    layout "portfolio"
    
    def index
        @portfolio_items = Portfolio.all
    end

    def angular
        @angualr_portfolio_items = Portfolio.angular
    end

    def new
        @portfolio_item = Portfolio.new
        3.times { @portfolio_item.technologies.build }
    end

    def create
        @portfolio_item = Portfolio.new(portfolio_params)

        respond_to do |format|
            if @portfolio_item.save
            format.html { redirect_to portfolios_path, notice: "Portfolio item was successfully created." }
            else
            format.html { render :new, status: :unprocessable_entity }
            end
        end
    end

    def edit
        @portfolio_item = Portfolio.find(params[:id])
    end

    def update
        @portfolio_item = Portfolio.find(params[:id])

        respond_to do |format|
          if @portfolio_item.update(portfolio_params)
            format.html { redirect_to portfolios_path(@portfolio_item), notice: "Portfolio item was successfully updated." }
          else
            format.html { render :edit, status: :unprocessable_entity }
          end
        end
    end

    def show
        @portfolio_item = Portfolio.find(params[:id])
    end

    def destroy
        @portfolio_item = Portfolio.find(params[:id])
        @portfolio_item.destroy

        respond_to do |format|
            format.html { redirect_to portfolios_url, notice: "Portfolio item was successfully destroyed." }
        end
    end

    private
    
    def portfolio_params
        params.require(:portfolio).permit(:title, 
                                        :subtitle, 
                                        :body,
                                        technologies_attributes: [:name])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def login_helper
        if current_user.is_a?(User)
            link_to "Logout", destroy_user_session_path, method: :delete
        else
            (link_to "Sign Up", new_user_registration_path) +
            "<br/>".html_safe +
            (link_to "Sign In", new_user_session_path)
        end
    end

    def source_helper(layout_name)
        if session[:source]
            greeting = "Thanks for visiting me from #{session[:source]} and you are on the #{layout_name} layout"
            content_tag(:p, greeting, class: "source-greeting")
        end
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Title:</strong>
    <%= blog.title.upcase %>
  </p>

  <p>
    <strong>Date:</strong>
    Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago
  </p>

  <p>
    <strong>Body:</strong>
    <%= blog.body %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= link_to blog.status, toggle_status_blog_path(blog) %>
  </p>

  <p><%= link_to "Show this blog", blog %></p>
  <hr>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blogs</h1>

<div id="blogs">
  <%= render @blogs %>
</div>

<%= link_to "New blog", new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog %>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>
  <%= button_to "Destroy this blog", @blog, method: :delete, "style": "margin-top: 15px;" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="keywords" content="<%= @seo_keywords %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <% if current_user %>
      <%= button_to "Logout", destroy_user_session_path, method: :delete  %>
    <% else %>
      <%= link_to "Register", new_user_registration_path %>
      <%= link_to "Login", new_user_session_path %>
    <% end %>


    <%# <%= render "shared/nav", location: 'top' %>
    <%= yield %>
    
    <%= source_helper("application") %>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="keywords" content="<%= @seo_keywords %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "blog", "data-turbo-track": "reload" %>
  </head>

  <body>
    
    <%= yield %>

    <%= render "shared/nav", location: 'top' %>

    <%= source_helper("blog") %>
  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="keywords" content="<%= @seo_keywords %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "portfolio", "data-turbo-track": "reload" %>
  </head>

  <body>
    
    <%= render "shared/nav", location: 'bottom' %>
    
    <%= yield %>

    <%= source_helper("portfolio") %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>

<p><%= number_to_phone "09420888977" %></p>
<p><%= number_to_currency "150" %></p>
<p><%= number_to_percentage "80.4" %></p>
<p><%= number_with_delimiter  "123456577" %></p>

app/views/pages/home.html.erb
<% if current_user %>
    <h1>Hi, <%= current_user.first_name %></h1>
<% else %>
    <h1>Hi, Guest</h1>
<% end %>



<h3>Blog Posts</h3>
<%= @posts.inspect %>

<h3>Skills</h3>
<%= @skills.inspect %>

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :subtitle, style: "display: block" %>
    <%= form.text_field :subtitle %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
<p><%= portfolio_item.subtitle %></p>
<p><%= portfolio_item.body %></p>
<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
<br/>
<%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %><br/><br/>
<%= button_to "Delete", portfolio_path(portfolio_item.id), method: :delete %>
<hr>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path %>

<%= render partial: 'portfolio_item', collection: @angualr_portfolio_items %>

app/views/portfolios/edit.html.erb
<h1>Edit this portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path %>

<%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1>Create a new portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>

<h1><%= @portfolio_item.title %></h1>

<em><%= @portfolio_item.subtitle %></em>

<p><%= @portfolio_item.body %></p>

<h2>Technologies Used:</h2>

<% @portfolio_item.technologies.each do |t| %>
    <p><%= t.name %></p>
<% end %>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
    <div><%= link_to "Home", root_path %></div>
    <div><%= link_to "About", about_path %></div>
    <div><%= link_to "Contact", contact_path %></div>
    <div><%= link_to "Blog", blogs_path %></div>
    <div><%= link_to "Portfolio", portfolios_path %></div>
</div>